### ISSUE TITLE
Indicate rule evaluation error

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmnlint#108]
When a lint rule throws an acutal error instead of reporting one the message is set to `Rule error: ...`. Other than that prefix, there is no way to tell whether an actual error occurred. I'd like something like a flag indicating that there was an actual error. For example:

```javascript
} catch (e) {
  console.error('rule <' + name + '> failed with error: ', e);

  return [
    {
      message: 'Rule error: ' + e.message,
      category: 'error',
      isRuleError: true
    }
  ];
}
```

---

Related to https://github.com/camunda/camunda-modeler/issues/3637

**Comment by nikku** [comment]
Could also be a separate category 'rule-evaluation-error'?

**Comment by nikku** [comment]
I'd be in for a separate category in this case. Call it `failure` or `rule-evaluation-error`.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmnlint/commit/820e954c8ab3bfac34a5e1fede07c4a1cf0c54ae
