### ISSUE TITLE
I don't understand the message: 'Incoming flows do not join'

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/bpmnlint#111]
__Describe the Bug__

In my BPMN diagram I find a warning on a Task: "Incoming flows do not join".

I don't understand what happens here.

![grafik](https://github.com/bpmn-io/bpmnlint/assets/7870843/4351151b-2c75-4e3f-9065-b74f266e2361)

__Steps to Reproduce__

1. do this
2. do that
3. now this happens

__Expected Behavior__

Provide a message like "Insert an XOR gateway to join the incoming sequence flows".

__Environment__

Camunda Web Modeler in Firefox 114.0.2 (64-Bit)

**Comment by ingorichtsmeier** [comment]
> A common misconception is that these flows have join semantics, but they don't.

Sorry @nikku, I don't understand this either. The sequence flows in my example split in the XOR Gateway C and join before the Task B again. Two sequence flows entering a task are (from the BPMN spec) allowed to join a splitting gateway from somewhere else.  

> Does https://github.com/bpmn-io/bpmnlint/blob/master/docs/rules/fake-join.md help you to make more sense of this error?

Yes, it does. And I tried to propose a message to get closer to the desired action (which is to insert a gateway where the sequence flows should join).

Maybe there is even a better message?

**Comment by nikku** [comment]
@ingorichtsmeier The point of the message + rule name `fake-join` is to convey that this is not the join semantics you expect from an exclusive gateway. The recommendation is to model the join explicitly. Not sure how we want to improve the message. 

What we want to do is to refer users to the rules page so they can learn more about individual rules. This is one of our future work items. Closing this issue.

**Comment by nikku** [comment]
Taking your original example:

![image](https://github.com/bpmn-io/bpmnlint/assets/58601/ab5f9085-b749-4367-9f22-92cb4958417a)

The message would be something like this:

> Incoming flows do not join _at task_?

**Comment by nikku** [comment]
After follow-up discussions the simplest way would be to link the documentation for this issue.

**Comment by nikku** [comment]
Proposal by Eric:

> Incoming flows should join at a gateway

**Comment by nikku** [comment]
Closing this (again). Let's follow up via https://github.com/bpmn-io/internal-docs/issues/856. 

We'd want to see the (short) error messages + [documentation](https://github.com/bpmn-io/bpmnlint/tree/main/docs/rules) as a unit.
