### ISSUE TITLE
Compiling Config Doesn't Work as Expected

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmnlint#112]
__Describe the Bug__

Compiling the config of a plugin using [compile-config](https://github.com/bpmn-io/bpmnlint/blob/main/lib/support/compile-config.js) doesn't work as expected when I compile outside of the plugin itself.

__Steps to Reproduce__

1. Create a plugin (e.g. [camunda-compat](https://github.com/camunda/bpmnlint-plugin-camunda-compat/))
2. Compile the config from somewhere else
```javascript
const compileConfig = require('bpmnlint/lib/support/compile-config');

const config = {
  extends: 'plugin:camunda-compat/all'
};

compileConfig(config)
```
3. The generated import statements import from `'rules/camunda-cloud/<rule>'` instead of `'bpmnlint-plugin-camunda-compat/rules/camunda-cloud/<rule>'` because the package directory evaluates to `.`. Since I'm in a different package these imports will fail.

__Expected Behavior__

I can do

```javascript
// my-npm-package/tasks/compile-config.js

const fs = require('fs');

const compileConfig = require('bpmnlint/lib/support/compile-config');

const config = {
  extends: 'plugin:camunda-compat/all'
};

compileConfig(config).then(code => fs.writeFileSync('lib/compiled-config.js', code));
```

without a custom resolver and the correct import statements will be generated.

__Environment__

- Library version: 9.0.0

**Comment by philippfromme** [comment]
`v9` of `bpmnlint` also doesn't work with [bpmnlint-loader](https://github.com/nikku/bpmnlint-loader/compare/master...philippfromme:bpmnlint-loader:failing) when compiling plugins. I think this should just work.

**Comment by philippfromme** [comment]
@nikku I'm pretty sure this is a valid use case that should be working. 🤔

**Comment by nikku** [comment]
Yep. A bug we should fix.

**Comment by philippfromme** [comment]
One of the issues I see is that the node resolver returns an absolute path (`C:\workspace\camunda\bpmnlint-plugin-camunda-compat\index.js`) instead of `bpmnlint-plugin-camunda-compat\index.js`.

**Comment by nikku** [comment]
@philippfromme I've created a test case to [verify external bundling in `bpmnlint-loader`](https://github.com/nikku/bpmnlint-loader/pull/new/test-external-bundling).

**Comment by philippfromme** [comment]
> @philippfromme I've created a test case to [verify external bundling in `bpmnlint-loader`](https://github.com/nikku/bpmnlint-loader/pull/5). This reproduces the error on 🪟.

Yes, similar to https://github.com/nikku/bpmnlint-loader/commit/d811e7a22acfcf24d7468d75ab2b6bb976954e5d.
