### ISSUE TITLE
Detect redundant terminate end events (`redundant-terminate-end`)

### ISSUE THREAD

**Issue by till-stadtler** [bpmn-io/bpmnlint#119]
#### The rule should detect the following modeling patterns

Incorrect use: The use of a terminate end event in a scope where no parallel processing can occur. This often happens in event-based subprocesses where users wrongly assume that a terminate end event terminates the parent scope.

Example of incorrect usage:
<img src="https://github.com/bpmn-io/bpmnlint/assets/117343024/760885b6-ad0b-4dd3-899f-3ce611c6b130" height="180"/>

Examples of correct usage:
1.
<img src="https://github.com/bpmn-io/bpmnlint/assets/117343024/70946921-beb2-4306-a94b-1b2ca178d08d" height="280"/>
2.
<img src="https://github.com/bpmn-io/bpmnlint/assets/117343024/ff4766c6-dea1-40d6-af3c-7098ac644f04" height="280"/>
3.
<img src="https://github.com/bpmn-io/bpmnlint/assets/117343024/3543aaff-db98-41ae-840c-9ebd262f3cae" height="280"/>

#### How does the rule improve the BPMN diagram?

It avoids the usage of redundant terminate end events.

#### Rule Details

* Name: `redundant-terminate-end`
* Default notification level: `warn`

Within a given scope, parallel processing can occur via:

- parallel gateways
- inclusive gateways
- conditional sequence flows
- non-interrupting boundary events
- non-interrupting start events of event-based subprocesses

If none of these elements exist in a given scope, a terminate end event is redundant, as no parallel processing can take place.

#### What alternatives did you consider? 

None

**Comment by nikku** [comment]
I think this is a great addition to the existing rule set. Especially, as you say, it contributes to eliminating a common BPMN miss-conception.

**Comment by nikku** [comment]
Working on this issue during spring cleaning I figure it is actually not that trivial to support advanced cases, because we'd need to do some elaborate backtracking to figure out where the event is redundant or not:

### Redundant

![image](https://github.com/bpmn-io/bpmnlint/assets/58601/6d166b66-05d6-4ac5-a13f-95a64ea06169)


### Not redundant

![image](https://github.com/bpmn-io/bpmnlint/assets/58601/a07b269a-ba89-46b1-bc12-1ed252944c57)

**Comment by nikku** [comment]
We'll ship our first stab on this issue (without elaborate flow analysis) via https://github.com/bpmn-io/bpmnlint/pull/127.
