### ISSUE TITLE
`no-implicit-end` rule reports false positives

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmnlint#140]
### Describe the Bug

The `no-implicit-end` rule reports false positives when compensations are modeled.

![image](https://github.com/user-attachments/assets/a45c8854-c54d-49ac-9a27-2789ced8506f)

### Steps to Reproduce

1. Model compensation boundary event with compensation activity
2. Implicit end is reported twice

### Expected Behavior

No implicit end reported

### Environment

- Library version: 10.3.0

---

Slack conversation: https://camunda.slack.com/archives/C0693F1NFK5/p1723790917001139

**Comment by nikku** [comment]
This should be simple to fix, moving to `ready` and flagging accordingly.

**Comment by abdul99ahad** [comment]
Is this required for all boundary events, or only for compensation boundary events and their associated activities?
