### ISSUE TITLE
Please add a manual "how to integrate bpmnlint as a plugin in camunda modeller".

### ISSUE THREAD

**Issue by FO-e-X** [bpmn-io/bpmnlint#24]
I'm not used in creating plugins for camunda modeller. I think, bpmnlint would be a great plugin for it, But I don't know how to use bpmnlint as plugin.

**Comment by nikku** [comment]
This is something we plan to do in the future, either as a plugin or as built in support (cf. https://github.com/camunda/camunda-modeler/issues/803).

**Comment by FO-e-X** [comment]
Thanks for your reply and this information. We will look forward to the modeller version including BPMNLint :)
