### ISSUE TITLE
Add bpmnlint playground

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmnlint#25]
Add a simple example project that allows users to:

* [ ] play around with bpmnlint using their diagrams
* [ ] implement new rules and try them out on-the-fly

**Comment by siffogh** [comment]
What about an online REPL like [this one](https://eslint.org/demo/)?

**Comment by nikku** [comment]
Created the [bpmnlint-playground](https://github.com/bpmn-io/bpmnlint-playground) project.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmnlint/commit/3af3de473a207ac33922a6017f6f48cd2e8ee153.
