### ISSUE TITLE
Exclude Event Sub-Process From No-Disconnected Rule

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmnlint#31]
We have a [`no-disconnected` rule](https://github.com/bpmn-io/bpmnlint/blob/master/rules/no-disconnected.js) that checks for flow elements that are not connected to other flow elements (usually an error).

The rule seems to apply to [event sub-processes](https://docs.camunda.org/manual/7.5/reference/bpmn20/subprocesses/event-subprocess/), too:

![foo](https://user-images.githubusercontent.com/7633572/63950788-ee0b8a80-ca7c-11e9-92d3-418fb0b6f353.jpg)

Those, by definition are never connected to other flow elements and should ignored in the check.

__Describe the solution you'd like__

* [ ] The linter excludes event sub-processes when checking for the `no-disconnected` rule

**Comment by oguzeroglu** [comment]
Fixed via #32
