### ISSUE TITLE
Add rule for exclusive=false

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmnlint#34]
see also https://github.com/camunda/camunda-modeler/issues/1501

**Comment by nikku** [comment]
If we implement this the rule should go to https://github.com/camunda/bpmnlint-plugin-camunda/issues/3. 

Can you provide some background information in https://github.com/camunda/bpmnlint-plugin-camunda/issues/3:

* Should it be an error or warning per default 
* How should the documentation look like? We need a description why this is a problem.

**Comment by nikku** [comment]
Closing this as it is moved to https://github.com/camunda/bpmnlint-plugin-camunda/issues/3.

**Comment by falko** [comment]
It should be a warning by default.

exclusive=true allows the Job Executor to execute jobs from the same 
process instance with multiple threads. This is generally not advisable 
and can cause problems, e.g. with parallel variable access.
