### ISSUE TITLE
Two pools look like a pool with two lanes

### ISSUE THREAD

**Issue by volkergersabeck** [bpmn-io/bpmnlint#38]
#### The rule should detect the following modeling patterns

* Create two pools with one lane each
* Position the pools right next to each other such that there is no gap between them anymore
* The pools look very similar to one pool with two lanes

#### How does the rule improve the BPMN diagram?

Since the two pools can be confused with one pool with two lanes, people would expect to be able to model sequence flows across the two pools. However, since only message flows are allowed in this case, they get confused and don't easily find the solution.

#### Rule Details

* Name: Adjacent pools
* Default notification level: `warning`

**Comment by nikku** [comment]
Is this issue based on actual user feedback? 

![image](https://user-images.githubusercontent.com/58601/70895502-59a74280-1fef-11ea-85a2-d099a60b8129.png)
