### ISSUE TITLE
A Gateway with only one source and one target should be clamined as warning

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-io/bpmnlint#40]
#### The rule should detect the following modeling patterns

A Gateway with only one source and one target should be claimed as warning

![image](https://user-images.githubusercontent.com/33545902/69867026-f2c32300-12a5-11ea-9a23-ea321b61558b.png)

#### How does the rule improve the BPMN diagram?
Better diagrams with unncessary Gateways

#### Rule Details

* Name: 
* Default notification level: `warning`

**Comment by nikku** [comment]
Happy to take a contribution that implements this rule.

**Comment by nikku** [comment]
Let's make this a `warning`, as suggested in the issue description.

**Comment by pinussilvestrus** [comment]
🚀
