### ISSUE TITLE
Document `no-inclusive-gateway` rule

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmnlint#44]
__Is your feature request related to a problem? Please describe__

Currently, `no-inclusive-gateway` is a rule in the recommended set. However, the documentation does not give grounds why this element should be disallowed. I couldn't find any sources which would discourage usage of this gateway. This has already caused confusion on [Camunda forum](https://forum.camunda.org/t/linter-plugin-error-element-has-disallowed-type-bpmn-inclusivegateway/23320).

__Describe the solution you'd like__

Add grounds why rule exists and should be used.

__Describe alternatives you've considered__

Remove the rule from the recommended set, but it has already been decided against in https://github.com/bpmn-io/bpmnlint/issues/41#issuecomment-580213851

__Additional context__

https://forum.camunda.org/t/linter-plugin-error-element-has-disallowed-type-bpmn-inclusivegateway/23320

**Comment by pinussilvestrus** [comment]
Related: https://github.com/bpmn-io/bpmnlint/issues/41#issuecomment-580213851

**Comment by barmac** [comment]
> Related: [#41 (comment)](https://github.com/bpmn-io/bpmnlint/issues/41#issuecomment-580213851)

Thanks! I will update the issue so that it does not contain removal request anymore.
