### ISSUE TITLE
no-disconnected rule should also check for existence of incoming and outgoing connection, where needed

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmnlint#70]
__Is your feature request related to a problem? Please describe__

* Currently the [no-disconnected](https://github.com/bpmn-io/bpmnlint/blob/master/rules/no-disconnected.js) rule checks whether an incoming **or** outgoing connection exists
* However, in many cases (not in all though), an incoming **and** outgoing connection is needed

__Describe the solution you'd like__

* no-disconnected rule should also check for existence of incoming **and** outgoing connection, where needed

__Describe alternatives you've considered__

Implement as seperate rule.

__Additional context__

**Comment by nikku** [comment]
This is not actionable at this point. Could you share a concrete example where incoming and outgoing are needed?

**Comment by MaxTru** [comment]
Hmmm. I double checked the BPMN spec to find some specifcs about this but was not succesful.

My assumption would be: 

* for example a service task should always have an input and an output sequence flow right?

However, as said - I did not find specifics about this in the spec. Will close for now. Maybe something to add it https://github.com/camunda/bpmnlint-plugin-camunda

**Comment by nikku** [comment]
That is my intuition. Any element that is not connected from a start event is an implicit start event in BPMN. We could argue whether that shall be a "discouraged" modeling pattern. I think it should. `no-implicit-start` or the like. Still, if we want this re-opened, please share a concrete instance of the issue you want highlighted / addressed.
