### ISSUE TITLE
Detect intermediate events overlapping tasks (looking like boundary events)

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmnlint#71]
__Is your feature request related to a problem? Please describe__

There were user reported problems, where an intermediateCatchEvent appeared visually as a boundary event. See https://jira.camunda.com/browse/SUPPORT-12954.

__Describe the solution you'd like__

Add a rule `non-boundary-event-overlaps-activity`, which would give a warning if a catchEvent visually appears as a boundary event (e.g., overlaps a task).

Such situations could happen, if for example the positioning of elements is updated manually. They could also result from a modeling bug or using of modeling APIs.

__Describe alternatives you've considered__

n/a

__Additional context__

Could have been used to identify https://jira.camunda.com/browse/SUPPORT-12954

**Comment by nikku** [comment]
Makes a lot of sense. I've seen these issues myself in the past, sometimes caused by different modeling tools being used in the tool chain.
