### ISSUE TITLE
Be Able to Provide More Information When Reporting Error

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmnlint#74]
__Is your feature request related to a problem? Please describe__

Recently, an optional `path` argument was added to `Reporter#report` to add more information to the error. In some cases there is still not enough information.

Example:

```xml
<bpmn:businessRuleTask />
```

This business rule task is missing an extension element that is required. The path could be specified as `[ 'extensionElements', 'values' 
 ]` but there is no information about what type of extension element is missing. For any missing property that is [`isMany=true`](https://github.com/bpmn-io/moddle/blob/cd23a5ffd7fbd7a10725d4807456a942b29d108d/docs/descriptor.md#qualifiers) the information about the type is missing.

__Describe the solution you'd like__

Either

* introduce a new concept of e.g. error types along with additional information (e.g. `{ type: 'missingProperty', missingPropertyType: 'foo:Bar' }`

or 

* introduce a way of providing arbitrary information when calling `Reporter#report` (e.g. `Reporter.report(id, message, path, { type: 'missingProperty', missingPropertyType: 'foo:Bar' }`)

__Describe alternatives you've considered__

__Additional context__

Assumptions about the error could be derived from the error message itself.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmnlint/pull/75 I guess?

**Comment by philippfromme** [comment]
Sorry, yes. 👍🏻
