### ISSUE TITLE
Accessing null for removed labels

### ISSUE THREAD

**Issue by epictecch** [bpmn-io/bpmnlint#76]
After resetting a label using `modeling.updateLabel(undefined)`, the `ModdleElement` looks like this: `{ $type: 'bpmndi:BPMNShape', label: null, ... }`

The label being `null` leads to accessing `null` in `traverse.js`:

```
rule <fake-join> failed with error:  TypeError: Cannot read properties of null (reading '$instanceOf')
    at is$7 (lintRules.js:37:1)
    at lintRules.js:53:1
    at Array.some (<anonymous>)
    at isAny$4 (lintRules.js:52:1)
    at check (lintRules.js:118:1)
    at traverse.enter (test-rule.js:70:1)
    at traverse (traverse.js:13:1)
    at traverse.js:32:1
    at Array.forEach (<anonymous>)
    at traverse (traverse.js:23:1)
```

This behaviour has been reported to the bpmn.io forum and has been classified as bug in bpmnlint. See [discussion](https://forum.bpmn.io/t/clearing-labels-results-in-errors-during-bpmnlint-run/7497).

**Comment by marstamm** [comment]
related to https://github.com/bpmn-io/bpmn-js/issues/1637

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js/issues/1637.

**Comment by nikku** [comment]
Fixed in bpmn-js@9.x: https://github.com/bpmn-io/bpmn-js/commit/c550d09d1d0ce9132ed51d38aa3764bf080ab290.
