### ISSUE TITLE
Doesn't check missing an end

### ISSUE THREAD

**Issue by linlyn2022** [bpmn-io/bpmnlint#88]
__Describe the Bug__

* The codes don't seem to detect the issue with an activity that is missing an end event.
I am attaching the bpmn file (in zip) for your convenience

![image](https://user-images.githubusercontent.com/111754994/185938683-6749b300-b791-4030-ab20-cab641fea9c8.png)
[Trial missing end.zip](https://github.com/bpmn-io/bpmnlint/files/9394969/Trial.missing.end.zip)

__Steps to Reproduce__

1. remove the check activity from the diagram and check for errors. The system spots three errors
2. add an activity to the XOR gateway and name the activity issue
3. check errors again. Only three errors are identified

__Expected Behavior__

* 1. There should be an end event attached to the activity issue (which is incorrectly named by the way. I have submitted to you my request for a rule about naming conventions).

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

* I used Google Chrome which is in the incognito mode
* The operating system of my laptop is Windows 10

**Comment by nikku** [comment]
Missing end events are valid BPMN. What rule (cf. [rules](https://github.com/bpmn-io/bpmnlint/tree/master/docs/rules#readme)) would you expect to catch this error? If you identified the rule, please open a respective issue in [bpmnlint](https://github.com/bpmn-io/bpmnlint).

**Comment by linlyn2022** [comment]
The rule is end-event-required, but it may not work all the time. I already
created an issue. Please check, Nico. Thanks!


Linying (Lin) Dong, Ph.D., Professor
Ted Rogers School of Information Technology Management
Toronto Metropolitan University
Tel: 416 9795000 ext. 554516
Office TRS2-072





Address: Room 2-072 575 Bay Street, Toronto, ON Canada M5G 2C5

Mailing Address: 350 Victoria Street, Toronto, ON, Canada M5B 2K3

* Strategic. Global. Collaborative. Research-driven*

**Comment by nikku** [comment]
My bad. Thanks for clarifying. Looking at our [`end-event-required` documentation](https://github.com/bpmn-io/bpmnlint/blob/master/docs/rules/end-event-required.md) this indeed looks like a valid issue.

We should capture the same thing for process start I believe (could be a separate issue):

![image](https://user-images.githubusercontent.com/58601/186091297-0616e869-416d-4e9d-9cc0-7ce7939c75f4.png)

**Comment by nikku** [comment]
Moving this one into our backlog, thanks for reporting!

**Comment by linlyn2022** [comment]
Thx! How long will it take to address the issue?

**Comment by nikku** [comment]
We welcome contributions to address this issue.

**Comment by nikku** [comment]
Will be addressed via https://github.com/bpmn-io/bpmnlint/pull/103.
